import { writeFileSync } from "node:fs";
import { type CheckResult, allResults } from "./assert.js";
import { REPORT_PATH } from "./config.js";

const ICON = { pass: "✅", fail: "❌", diverge: "⚠️", skip: "⏭️" } as const;

/** Writes the report header + a placeholder, before any check runs (durable skeleton). */
export function writeSkeleton(): void {
  const header = [
    "# PR #12 — Live Verification Report",
    "",
    "> Generated by `npm run verify:live` against a disposable Mealie. Re-run before every release.",
    "",
    "_Run in progress — results will be filled in on completion._",
    "",
  ].join("\n");
  writeFileSync(REPORT_PATH, header);
}

/** Escapes a detail string for a Markdown table cell. */
function cell(detail: string): string {
  return detail.replace(/\|/g, "\\|").replace(/\n/g, " ");
}

/** Renders one result row. */
function row(r: CheckResult): string {
  return `| ${ICON[r.status]} | ${r.id} | ${r.owedPr} | ${r.title} | ${cell(r.detail)} |`;
}

/** Durable findings from the live pass: the one real bug fixed, plus Mealie behaviors confirmed/discovered. */
const FINDINGS = [
  "## Findings",
  "",
  "**Bug found & fixed (TDD):**",
  "",
  "- `recipe_update` reported failure on a rename. Mealie regenerates a recipe's slug when `name` changes, so the handler's post-update re-fetch by the *original* slug 404'd. Fixed to return the PUT/PATCH response (the updated recipe, with the new slug). Regression test in `recipe-update.test.ts`.",
  "",
  "**Quirks-ledger confirmed against the live instance:**",
  "",
  "- **Bare-slug create** — `POST /api/recipes` returns a bare quoted slug string; `recipe_create` re-fetches into a full object (C-RECIPE-CREATE).",
  "- **Error-on-200** — `SuccessResponse{error}` (group_seed, backups, maintenance) and `EmailSuccess{success}` (email test) both map to `isError` (C-SEED, C-MAINT-CLEAN, C-EMAIL-TEST).",
  "- **Integer meal-plan ids** — `ReadPlanEntry.id` is a number, not a uuid (C-MEALPLAN).",
  "- **`EmailInitationResponse`** (verbatim upstream typo) — surfaced with its `{success}` shape (C-INVITE).",
  "- **`secretSafeErrorResult`** — a real 422 carrying a submitted password surfaces status-only, no secret leak (C-USER-PW); write-only `apiKey` never echoed (C-AIPROVIDER, C-ADMIN-AIKEY); reset/api tokens shown exactly once (C-ADMIN-ACTIONS, C-USER-TOKEN).",
  "",
  "**Mealie behaviors to be aware of (not bugs in this server):**",
  "",
  "- Uploaded recipe assets do not appear in `recipe.recipeAssets` on a GET; the asset POST returns the descriptor (read assets via `recipe_media`).",
  "- `householdsWithTool` is not settable via the organizer/tool endpoints (create and PUT both return `[]`); it is managed per-household.",
  "- `GET /api/groups/reports` returns rows only when `report_type` is supplied; unfiltered it is empty.",
  "- Mealie normalizes a webhook `scheduledTime` from `HH:MM` to `HH:MM:SS`.",
  "- A backup restore can momentarily restart the instance; the harness waits for `/api/app/about` to return before continuing.",
  "",
];

/** Run metadata recorded in the report header. */
export type ReportMeta = { pinnedTag: string; runningVersion: string; specParity: string };

/** Writes the final report from collected results + run metadata. */
export function writeReport(meta: ReportMeta): void {
  const rows = allResults();
  const counts = rows.reduce<Record<string, number>>((acc, r) => {
    acc[r.status] = (acc[r.status] ?? 0) + 1;
    return acc;
  }, {});
  const lines = [
    "# PR #12 — Live Verification Report",
    "",
    `**Image:** \`ghcr.io/mealie-recipes/mealie:${meta.pinnedTag}\` · **Running version:** \`${meta.runningVersion}\``,
    `**Spec parity:** ${meta.specParity}`,
    `**Tally:** ${counts.pass ?? 0} pass · ${counts.fail ?? 0} fail · ${counts.diverge ?? 0} diverge · ${counts.skip ?? 0} skip`,
    "",
    "Each check re-fetches and asserts the named owed behavior — a pass would FAIL if the guarded bug were present.",
    "",
    "| | ID | Owed PR | Check | Evidence / detail |",
    "|---|---|---|---|---|",
    ...rows.map(row),
    "",
    ...FINDINGS,
    "## Teardown",
    "",
    "`docker compose down -v` runs automatically in the harness `finally`. The container is disposable — never aimed at a real instance.",
    "",
  ];
  writeFileSync(REPORT_PATH, lines.join("\n"));
}
