import { writeFileSync } from "node:fs";
import { type CheckResult, allResults } from "./assert.js";
import { REPORT_PATH } from "./config.js";

const ICON = { pass: "✅", fail: "❌", diverge: "⚠️", skip: "⏭️" } as const;

/** Writes the report header + a placeholder, before any check runs (durable skeleton). */
export function writeSkeleton(): void {
  const header = [
    "# PR #12 — Live Verification Report",
    "",
    "> Generated by `npm run verify:live` against a disposable Mealie. Re-run before every release.",
    "",
    "_Run in progress — results will be filled in on completion._",
    "",
  ].join("\n");
  writeFileSync(REPORT_PATH, header);
}

/** Escapes a detail string for a Markdown table cell. */
function cell(detail: string): string {
  return detail.replace(/\|/g, "\\|").replace(/\n/g, " ");
}

/** Renders one result row. */
function row(r: CheckResult): string {
  return `| ${ICON[r.status]} | ${r.id} | ${r.owedPr} | ${r.title} | ${cell(r.detail)} |`;
}

/** Run metadata recorded in the report header. */
export type ReportMeta = { pinnedTag: string; runningVersion: string; specParity: string };

/** Writes the final report from collected results + run metadata. */
export function writeReport(meta: ReportMeta): void {
  const rows = allResults();
  const counts = rows.reduce<Record<string, number>>((acc, r) => {
    acc[r.status] = (acc[r.status] ?? 0) + 1;
    return acc;
  }, {});
  const lines = [
    "# PR #12 — Live Verification Report",
    "",
    `**Image:** \`ghcr.io/mealie-recipes/mealie:${meta.pinnedTag}\` · **Running version:** \`${meta.runningVersion}\``,
    `**Spec parity:** ${meta.specParity}`,
    `**Tally:** ${counts.pass ?? 0} pass · ${counts.fail ?? 0} fail · ${counts.diverge ?? 0} diverge · ${counts.skip ?? 0} skip`,
    "",
    "Each check re-fetches and asserts the named owed behavior — a pass would FAIL if the guarded bug were present.",
    "",
    "| | ID | Owed PR | Check | Evidence / detail |",
    "|---|---|---|---|---|",
    ...rows.map(row),
    "",
    "## Teardown",
    "",
    "`docker compose down -v` runs automatically in the harness `finally`. The container is disposable — never aimed at a real instance.",
    "",
  ];
  writeFileSync(REPORT_PATH, lines.join("\n"));
}
